version: '3.8'

services:
  mcp-upbit:
    build: .
    ports:
      - "${PORT:-10000}:${PORT:-10000}"
    environment:
      - HOST=0.0.0.0
      - PORT=${PORT:-10000}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-10000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s