version: '3.8'

services:
  gmail-mcp-server:
    build: .
    ports:
      - "11011:11011"
    environment:
      - HOST=0.0.0.0
      - PORT=11011
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
