services:
  duckduckgo-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: duckduckgo-mcp-server
    ports:
      - "11005:11005"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "uv", "run", "python", "-c", "import httpx; httpx.get('http://localhost:11005/mcp', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  mcp-network:
    driver: bridge
