version: '3.8'

services:
  mcp-server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./simple_mcp_server.py:/app/simple_mcp_server.py
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
